# Generated by Django 2.2.10 on 2020-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
